apiVersion: v1
kind: Service
metadata:
  name: cloudedu-service
  namespace: cloudedu
spec:
  type: NodePort
  selector:
    app: cloudedu
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
